title: OHLC Candlestick Patterns Docs
description: Docs for OHLC Candlestick Patterns package
theme: docs
logo: https://github.com/przemyslawbak/OHLC_Candlestick_Patterns/blob/main/Candlestick_Patterns/stock-price-candlestick-graph-pngrepo-com.ico
favicon_ico: https://github.com/przemyslawbak/OHLC_Candlestick_Patterns/blob/main/Candlestick_Patterns/stock-price-candlestick-graph-pngrepo-com.ico

url: https://github.com/przemyslawbak/OHLC_Candlestick_Patterns

aux_links:
  Repository: https://github.com/przemyslawbak/OHLC_Candlestick_Patterns
