# Credits: https://just-the-docs.github.io/just-the-docs/docs/configuration/

# Basic config
title: OHLC Candlestick Patterns Docs
description: Docs for OHLC Candlestick Patterns package
theme: docs
url: "https://github.com/przemyslawbak/OHLC_Candlestick_Patterns"
aux_links:
  Repository: "https://github.com/przemyslawbak/OHLC_Candlestick_Patterns"

# Set a path/url to a logo that will be displayed instead of the title
logo: "https://github.com/przemyslawbak/OHLC_Candlestick_Patterns/blob/main/Candlestick_Patterns/stock-price-candlestick-graph-pngrepo-com.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "https://github.com/przemyslawbak/OHLC_Candlestick_Patterns/blob/main/Candlestick_Patterns/stock-price-candlestick-graph-pngrepo-com.ico"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# This uses the color $red-000 for the background of the callout, and $red-300 for the title and box decoration
callouts:
  warning:
    title: Warning
    color: red

# Override the default opacity of the background for a particular callout
callouts:
  custom:
    color: pink
    opacity: 0.3
